name: Build Windows EXE

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false # Turned off temporarily to prevent cache confusion

      - name: Download dependencies
        working-directory: ./acexy # <--- THIS IS THE FIX
        run: go mod download

      - name: Build Executable
        working-directory: ./acexy # <--- AND HERE
        run: go build -v -ldflags "-s -w" -o acexy.exe .

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Acexy-Windows-EXE
          path: acexy/acexy.exe # <--- Point it to the subfolder to grab the file
